<a href="https://colab.research.google.com/github/prashant3094/Data-Analysis-with-Python-/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

In [11]:
import sys
import numpy as np

## Basic Numpy Arrays

In [12]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [13]:
a = np.array([1, 2, 3, 4])

In [14]:
b = np.array([0, .5, 1, 1.5, 2])

In [15]:
a[0], a[1]

(1, 2)

In [16]:
a[0:]

array([1, 2, 3, 4])

In [17]:
a[1:3]

array([2, 3])

In [18]:
a[1:-1]

array([2, 3])

In [19]:
a[::2]

array([1, 3])

In [20]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [21]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [22]:
b[[0, 2, -1]]

array([0., 1., 2.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Array Types

In [23]:
a

array([1, 2, 3, 4])

In [24]:
a.dtype

dtype('int64')

In [25]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [26]:
b.dtype

dtype('float64')

In [27]:
np.array([1, 2, 3, 4], dtype=np.float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([1., 2., 3., 4.])

In [28]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [29]:
c = np.array(['a', 'b', 'c'])

In [30]:
c.dtype

dtype('<U1')

In [31]:
d = np.array([{'a': 1}, sys])

In [32]:
d.dtype

dtype('O')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Dimensions and shapes

In [33]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [34]:
A.shape

(2, 3)

In [35]:
A.ndim

2

In [36]:
A.size

6

In [37]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [38]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [39]:
B.shape

(2, 2, 3)

In [40]:
B.ndim

3

In [41]:
B.size

12

If the shape isn't consistent, it'll just fall back to regular Python objects:

In [42]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  import sys


In [43]:
C.dtype

dtype('O')

In [44]:
C.shape

(2,)

In [45]:
C.size

2

In [46]:
type(C[0])

list

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Indexing and Slicing of Matrices

In [47]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [48]:
A[1]

array([4, 5, 6])

In [49]:
A[1][0]

4

In [50]:
# A[d1, d2, d3, d4]

In [51]:
A[1, 0]

4

In [52]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [54]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [55]:
A[:2, 2:]

array([[3],
       [6]])

In [56]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
A[1] = np.array([10, 10, 10])

In [58]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [59]:
A[2] = 99

In [60]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Summary statistics

In [61]:
a = np.array([1, 2, 3, 4])

In [62]:
a.sum()

10

In [63]:
a.mean()

2.5

In [64]:
a.std()

1.118033988749895

In [65]:
a.var()

1.25

In [66]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [67]:
A.sum()

45

In [68]:
A.mean()

5.0

In [69]:
A.std()

2.581988897471611

In [70]:
A.sum(axis=0)

array([12, 15, 18])

In [71]:
A.sum(axis=1)

array([ 6, 15, 24])

In [72]:
A.mean(axis=0)

array([4., 5., 6.])

In [73]:
A.mean(axis=1)

array([2., 5., 8.])

In [74]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [75]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

And [many more](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html#array-methods)...

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Broadcasting and Vectorized operations

In [76]:
a = np.arange(4)

In [77]:
a

array([0, 1, 2, 3])

In [78]:
a + 10

array([10, 11, 12, 13])

In [79]:
a * 10

array([ 0, 10, 20, 30])

In [80]:
a

array([0, 1, 2, 3])

In [81]:
a += 100

In [82]:
a

array([100, 101, 102, 103])

In [83]:
l = [0, 1, 2, 3]

In [84]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [85]:
a = np.arange(4)

In [86]:
a

array([0, 1, 2, 3])

In [87]:
b = np.array([10, 10, 10, 10])

In [88]:
b

array([10, 10, 10, 10])

In [89]:
a + b

array([10, 11, 12, 13])

In [90]:
a * b

array([ 0, 10, 20, 30])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Boolean arrays
_(Also called masks)_

In [91]:
a = np.arange(4)

In [92]:
a

array([0, 1, 2, 3])

In [93]:
a[0], a[-1]

(0, 3)

In [94]:
a[[0, -1]]

array([0, 3])

In [95]:
a[[True, False, False, True]]

array([0, 3])

In [96]:
a

array([0, 1, 2, 3])

In [97]:
a >= 2

array([False, False,  True,  True])

In [98]:
a[a >= 2]

array([2, 3])

In [99]:
a.mean()

1.5

In [100]:
a[a > a.mean()]

array([2, 3])

In [101]:
a[~(a > a.mean())]

array([0, 1])

In [102]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [103]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [104]:
A = np.random.randint(100, size=(3, 3))

In [105]:
A

array([[51, 18, 25],
       [49, 65, 93],
       [75, 24, 54]])

In [106]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([51, 25, 65, 75, 54])

In [107]:
A > 30

array([[ True, False, False],
       [ True,  True,  True],
       [ True, False,  True]])

In [108]:
A[A > 30]

array([51, 49, 65, 93, 75, 54])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Linear Algebra

In [109]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [110]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [111]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [112]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [113]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [114]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [115]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Size of objects in Memory

### Int, floats

In [116]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [117]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [118]:
# Numpy size is much smaller
np.dtype(int).itemsize

8

In [119]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [120]:
np.dtype(float).itemsize

8

### Lists are even larger

In [121]:
# A one-element list
sys.getsizeof([1])

80

In [122]:
# An array of one element in numpy
np.array([1]).nbytes

8

### And performance is also important

In [123]:
l = list(range(100000))

In [124]:
a = np.arange(100000)

In [125]:
%time np.sum(a ** 2)

CPU times: user 0 ns, sys: 1.03 ms, total: 1.03 ms
Wall time: 1.1 ms


333328333350000

In [126]:
%time sum([x ** 2 for x in l])

CPU times: user 45.1 ms, sys: 4.71 ms, total: 49.8 ms
Wall time: 51.8 ms


333328333350000

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Useful Numpy functions

### `random` 

In [127]:
np.random.random(size=2)

array([0.16698958, 0.93523468])

In [128]:
np.random.normal(size=2)

array([-1.0891964 , -0.62814814])

In [129]:
np.random.rand(2, 4)

array([[0.07740336, 0.72685454, 0.92591399, 0.80169184],
       [0.86184373, 0.36081211, 0.20715735, 0.78811187]])

---
### `arange`

In [130]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [131]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [132]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

---
### `reshape`

In [133]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [134]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

---
### `linspace`

In [135]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [136]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [137]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

---
### `zeros`, `ones`, `empty`

In [138]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [139]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [140]:
np.zeros((3, 3), dtype=np.int)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [141]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [142]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [143]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [144]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

---
### `identity` and `eye`

In [145]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [146]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [147]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [148]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [149]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [150]:
"Hello World"[6]

'W'

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)